In [67]:
import numpy as np
np.random.seed(42)

In [91]:
class Affine():
    def __init__(self, in_dim: int, out_dim: int):
        """
        in_dim : explanatory_variable_dim_
        out_dim : target_variable_dim_
        w : parameter
        b : bias
        dw : parameter_gradient
        db : bias_gradient
        """
        self.in_dim = in_dim
        self.out_dim = out_dim
        
        self.w = np.random.randn(self.in_dim, self.out_dim)
        self.b = np.zeros(self.out_dim, dtype=float)

        self.dx , self.dw, self.db = None, None, None

    def __call__(self, x: np.ndarray) -> np.ndarray:
        """ forward_propagation
        x : input_data_ (batch_size, in_dim)
        out : target_data_ (batch_size, out_dim)
        """
        self.x = x
        self.out = np.dot(self.x, self.w) + self.b
        self.param = {'w' : self.w, 'b' : self.b}
        return  self.out

    def backward(self, grad: np.ndarray) -> np.ndarray:
        """ back_propagation
        grad : previous_gradient_ (batch_size, out_dim)
        dx : gradient_ (batch_size, in_dim)
        """
        self.dx = np.dot(grad, self.w.T)
        self.dw = np.dot(self.x.T, grad)
        self.db = np.sum(self.b)
        self.grad_param = {'x' : self.dx, 'w' : self.dw, 'b' : self.db}
        return self.dx

In [92]:
# demo_data
x = np.random.randn(2,3) # (batch_size, input_dim)
x

array([[-0.47917424, -0.18565898, -1.10633497],
       [-1.19620662,  0.81252582,  1.35624003]])

In [93]:
# forward_propagation
_, dim = x.shape
out_dim = 4
affine = Affine(dim, 4)
out = affine(x)
out

array([[ 2.86572469, -1.67571689, -0.26293846,  0.34943692],
       [-3.17322093,  1.1639588 , -0.34364427,  1.63748416]])

In [94]:
# parameters
affine.param

{'w': array([[-0.07201012,  1.0035329 ,  0.36163603, -0.64511975],
        [ 0.36139561,  1.53803657, -0.03582604,  1.56464366],
        [-2.6197451 ,  0.8219025 ,  0.08704707, -0.29900735]]),
 'b': array([0., 0., 0., 0.])}

In [95]:
# demo_grad
grad = np.random.randn(2, 4)
grad

array([[ 0.09176078, -1.98756891, -0.21967189,  0.35711257],
       [ 1.47789404, -0.51827022, -0.8084936 , -0.50175704]])

In [96]:
#back_propagation
dx = affine.backward(grad)
dx

array([[-2.31102014, -2.45716783, -1.99987879],
       [-0.59521158, -1.01911999, -4.21802123]])

In [98]:
# grad_parameters
affine.grad_param

{'x': array([[-2.31102014, -2.45716783, -1.99987879],
        [-0.59521158, -1.01911999, -4.21802123]]),
 'w': array([[-1.81183605,  1.57235009,  1.07238651,  0.42908595],
        [ 1.18379086, -0.05209792, -0.61613787, -0.47399171],
        [ 1.90286091,  1.49601819, -0.85348069, -1.07558911]]),
 'b': 0.0}