In [36]:
import numpy as np
np.random.seed(42)

In [37]:
import numpy as np
np.random.seed(42)


class Affine():
    def __init__(self, in_dim: int, out_dim: int):
        """
        in_dim : explanatory_variable_dim_
        out_dim : target_variable_dim_
        dw : parameter_gradient_
        db : bias_gradient_
        """
        self.in_dim = in_dim
        self.out_dim = out_dim
        
        self.weight = np.random.randn(in_dim, out_dim)
        self.bias = np.zeros(out_dim, dtype=float)

        self.dx , self.dw, self.db = None, None, None

    def __call__(self, x: np.ndarray) -> np.ndarray:
        """ forward_propagation
        x : input_data_ (batch_size, in_dim)
        output : output_data_ (batch_size, out_dim)
        """
        self.x = x
        output = np.dot(self.x, self.weight) + self.bias
        self.param = {'w' : self.weight, 'b' : self.bias}
        return  output

    def backward(self, grad: np.ndarray) -> np.ndarray:
        """ back_propagation
        grad : previous_gradient_ (batch_size, out_dim)
        dx : gradient_ (batch_size, in_dim)
        """
        dx = np.dot(grad, self.weight.T)
        dw = np.dot(self.x.T, grad)
        db = np.sum(self.bias)
        self.grad_param = {'w' : dw, 'b' : db}
        return dx

In [38]:
# create_data
x = np.random.randn(2,3) # (batch_size, input_dim)

# forward_propagation
_, dim = x.shape
out_dim = 4
affine = Affine(dim, 4)
out = affine(x)
print('-------------  Affine_output  ------------\n',out)
print()
# parameters
print('----------------  params  ----------------\n', affine.param)

-------------  Affine_output  ------------
 [[-0.26871803  0.0814023  -0.92264842  0.73757   ]
 [ 2.9175661   1.40953049 -0.53453859  1.20075926]]

----------------  params  ----------------
 {'w': array([[ 1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024],
       [-1.72491783, -0.56228753, -1.01283112,  0.31424733]]), 'b': array([0., 0., 0., 0.])}


In [39]:
# demo_grad
grad = np.random.randn(2, 4)
#back_propagation
dx = affine.backward(grad)
print('----------------  grad  -------------\n', dx)
print()
# grad_parameters
print('---------------params_grad-----------\n',affine.grad_param)

----------------  grad  -------------
 [[-3.32839592  1.86515132  0.80498339]
 [-0.67100392  0.28830778  1.27086243]]

---------------params_grad-----------
 {'w': array([[-0.34818094, -2.87144526, -0.10110266,  0.05679213],
       [ 0.10973536,  0.52888078, -0.07517785,  0.0052439 ],
       [-0.60392763, -0.58114671,  1.07674402, -0.1722038 ]]), 'b': 0.0}
