In [143]:
import sys
import os
import numpy as np

In [144]:
class ReLu():
    def __init__(self):
        self.mask = None

    def __call__(self, x: np.ndarray) -> np.ndarray:
        """ forward
        self.mask : boolean_mask_ where(x>0, True)
        """
        self.mask  = [x > 0]
        dims = list(x.shape)
        out = np.zeros(dims)
        out[x > 0] = x[x > 0]
        return out

    def backward(self, grad: np.ndarray) -> np.ndarray:
        mask = self.mask[0]
        dx = grad * mask
        return dx

In [145]:
# Create data
batch, channel, dim = np.arange(2,5)
x = np.random.randn(batch, channel, dim)
# ReLu forward
relu = ReLu()
out = relu(x)
print('--------------------- output --------------------\n',out)
print()
# Create demo gradient
grad = np.random.randn(batch, channel, dim)
dx = relu.backward(grad)
print('----------------------- dx ----------------------\n', dx)

--------------------- output --------------------
 [[[0.49671415 0.         0.64768854 1.52302986]
  [0.         0.         1.57921282 0.76743473]
  [0.         0.54256004 0.         0.        ]]

 [[0.24196227 0.         0.         0.        ]
  [0.         0.31424733 0.         0.        ]
  [1.46564877 0.         0.0675282  0.        ]]]

----------------------- dx ----------------------
 [[[-0.54438272  0.         -1.15099358  0.37569802]
  [-0.         -0.         -0.60170661  1.85227818]
  [-0.         -1.05771093  0.         -0.        ]]

 [[ 0.2088636  -0.         -0.          0.        ]
  [ 0.          0.17136828 -0.         -0.        ]
  [-1.47852199 -0.         -0.46063877  0.        ]]]
